allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  protobufjs: true
  sharp: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@dynamic-labs/assert-package-version@4.88.6'
  - '@dynamic-labs/embedded-wallet-evm@4.88.6'
  - '@dynamic-labs/embedded-wallet@4.88.6'
  - '@dynamic-labs/ethereum-core@4.88.6'
  - '@dynamic-labs/ethereum@4.88.6'
  - '@dynamic-labs/iconic@4.88.6'
  - '@dynamic-labs/locale@4.88.6'
  - '@dynamic-labs/logger@4.88.6'
  - '@dynamic-labs/multi-wallet@4.88.6'
  - '@dynamic-labs/rpc-providers@4.88.6'
  - '@dynamic-labs/sdk-react-core@4.88.6'
  - '@dynamic-labs/solana-core@4.88.6'
  - '@dynamic-labs/store@4.88.6'
  - '@dynamic-labs/sui-core@4.88.6'
  - '@dynamic-labs/types@4.88.6'
  - '@dynamic-labs/utils@4.88.6'
  - '@dynamic-labs/waas-evm@4.88.6'
  - '@dynamic-labs/waas@4.88.6'
  - '@dynamic-labs/wallet-book@4.88.6'
  - '@dynamic-labs/wallet-connector-core@4.88.6'
  - '@dynamic-labs/webauthn@4.88.6'
